### ISSUE TITLE
SVG-URI doesn't works for react-native: "0.40.0" and react-native-svg: "^5.1.4"

### ISSUE THREAD

**Issue by AkshatSharda** [matc4/react-native-svg-uri#33] opened 2017-01-31 06:38 UTC
Hey, I am using the svg-uri for the react native: 0.40.0 and react-native-svg: 5.1. When i try to render the svg, it throws an error "No Component found for view with name RNSVGViewBox".
<img width="820" alt="screen shot 2017-01-31 at 12 05 54 pm" src="https://cloud.githubusercontent.com/assets/23695359/22454678/aecc48dc-e7ad-11e6-968c-6a2bd0d84154.png">

**Comment by NicolasLourenco** [comment] 2017-02-01 09:42
Same issue with same environnement for me.

**Comment by AkshatSharda** [comment] 2017-02-02 08:44
@NicolasLourenco any progress?

**Comment by tanthanh289** [comment] 2017-02-04 16:42
for me, this works:
- react-native 0.40.0
- react-native-svg 5.1.3
- react-native-svg-uri 1.2.0

**Comment by kiki-le-singe** [comment] 2017-02-22 10:30
Hi!

Doesn't work for me too.

- react 15.4.2
- react-native 0.41.2
- react-native-svg 5.1.5
- react-native-svg-uri 1.2.0

How did I install it?

- yarn add react-native-svg
- yarn add react-native-uri
- react-native link react-native-svg

Thanks

**Comment by oakis** [comment] 2017-02-22 17:27
I also have this problem with:

* react-native 0.40.0
* react-native-svg-uri 1.2.0

**Comment by AkshatSharda** [comment] 2017-02-22 18:24
@kiki-le-singe
Use the following version of react-native-svg. It works for me.
- react-native 0.41.1
- react-native-svg 5.1.3
- react-native-svg-uri 1.2.0

**Comment by craigcosmo** [comment] 2017-02-25 09:52
sam problem

**Comment by risuiar** [comment] 2017-02-28 09:40
same problem

- react-native 0.41.2

- react-native-svg 5.1.5

- react-native-svg-uri 1.2.0

**Comment by lucianomlima** [comment] 2017-03-05 22:59
Same problem here.

* react 15.4.1
* react-native 0.42.0
* react-native-svg 5.1.5
* react-native-svg-uri 1.2.0

**Comment by mariotacke** [comment] 2017-03-06 00:26
I forgot to rebuild after I installed the lib... D'oh.

**Comment by cloudZQY** [comment] 2017-03-07 08:57
@lucianomlima  
but this version have some problem #37 .
react-native-svg-uri can run well in react-native-svg. but this npm package have a low version Dependent. I suggest author edit packager.json to close this issue.

**Comment by lucianomlima** [comment] 2017-03-08 20:47
@cloudZQY Humm... For me works well in both platforms.
I'll try to update later to another 5.x version to test.

**Comment by Noitidart** [comment] 2017-03-14 20:30
I get the RNSVGViewBox error on Android (I could not test on iOS).

**Comment by eduardomoroni** [comment] 2017-03-26 20:38
Does anyone knows how to solved it?

**Comment by markallancourtney** [comment] 2017-04-26 05:17
Like @mariotacke mentioned,

After restarting the packager, this library started working as advertised.

**Comment by Kalyani518** [comment] 2017-04-26 09:20
same problem
<img width="376" alt="screen shot 2017-04-26 at 2 50 18 pm" src="https://cloud.githubusercontent.com/assets/12053917/25427293/b5f91f3e-2a8f-11e7-9d99-96ba43a4f316.png">

**Comment by kirillpisarev** [comment] 2017-05-02 12:54
There seems to be a problem with the `viewBox` property of `svg` tag
see [react-native-svg/issues/301](https://github.com/react-native-community/react-native-svg/issues/301)

**Comment by stefanoeb** [comment] 2017-05-17 13:03
The problem is that around the `^5.1.4` version of `react-native-svg` (not sure exactly when), they changed their package name used by `rnpm`.
In short, if you are using newer versions of `react-native-svg`, it will throw this error because this lib uses an older version (`4.3.1`) and in that time, the java package was called `com.horcrux.svg.RnSvgPackage`, but it changed to `com.horcrux.svg.SvgPackage`.

So... two options: 
- either downgrade `react-native-svg` (but as some friends told us, there's some issues #37 )
- update `react-native-svg` version of this package (will send a PR in short, no issues found so far)

**Comment by almundomob** [comment] 2017-05-19 12:13
Hello @stefanoeb , this library has no dependency with the package name of react-native-svg (com.horcrux.svg.RnSvgPackage or com.horcrux.svg.SvgPackage).
Also in the package.json ^4.3.1 the minimum version is 4.3.1, but you can install a newer.
Maybe the problem is in another place?

Thanks

**Comment by matc4** [comment] 2017-05-19 12:18
Hello @stefanoeb  , this library has no dependency with the package name of react-native-svg (com.horcrux.svg.RnSvgPackage or com.horcrux.svg.SvgPackage).
Also in the package.json ^4.3.1 the minimum version is 4.3.1, but you can install a newer.
Maybe the problem is in another place?

Thanks

**Comment by stefanoeb** [comment] 2017-05-19 12:25
Yes it is ^4.3.1.
But the `^` sign only does update until 4.x.x, and the problem is solved in 5.1.4.
Those `com.horcrux.svg.SvgPackage` are the names of the packages installed for android, via the command `react-native link react-native-svg` present in the README. And the problem is that this android libs changed their names.

Cheers

**Comment by matc4** [comment] 2017-05-19 12:30
Ahh Ok, so the problem is when install the 4.x.x version, link react-native-svg and after that, upgrade to 5.x.x of react-native-svg, that cause a crash in package names.

**Comment by stefanoeb** [comment] 2017-05-19 12:45
Yes, in my case, I already had 5.x.x linked and then installed `react-native-svg-uri` (react-native link said that it was already linked).

Probably is the same case with the other people above.

**Comment by mndewitt** [comment] 2017-06-06 16:53
Just to review a stopgap fix until #58 is merged:

- `react-native unlink react-native-svg`
- `yarn add react-native-svg` (should be v. 5+)
- `react-native link react-native-svg`
- `react-native run-ios` (to rebuild native code)

this worked for me w/ RN 0.44.2 and react-native-svg-uri 1.2.0

**Comment by stefanoeb** [comment] 2017-06-06 17:33
Yeah, the error seem to occur only on android

**Comment by matc4** [comment] 2017-08-27 20:47
Fix in the last release!

**Closed by matc4** 2017-08-27 20:47 UTC
